#version: "3.9"

services:
  proton:
    build: .
    container_name: proton_service
    ports:
      - "0.0.0.0:8100:8100"
      - "8100-8200:8100-8200"
    cap_add:
      - NET_ADMIN             # Required for OpenVPN to modify network interfaces and routes
    # devices:                # Usually not needed if mknod in app/run works for /dev/net/tun
    #   - "/dev/net/tun:/dev/net/tun"
    env_file:
      - .env                  # Load environment variables from .env file
    restart: unless-stopped
    # Optional: Uncomment and set specific DNS if needed (will be used by container *before* VPN might change it)
    # dns:
    #   - 1.1.1.1
    #   - 1.0.0.1

